name: Practice Job

on:
    workflow_dispatch:
    # push:
    #     branches: [main]

jobs:

    Job1:
        runs-on: ubuntu-slim

        steps:
            - name: This is 1st Job
              run: echo "My name is Pritesh"

    Job2:
        needs: Job1
        runs-on: ubuntu-slim

        steps:
            - name: This is 2nd Job
              run: docker --version
        
    Job3:
        needs: Job2
        runs-on: ubuntu-slim

        steps:
            - name: This is 3rd Job
              run: git --version
        
    Job4:
        needs: Job3
        runs-on: ubuntu-slim
        
        steps:
            - name: This is 4th Job
              run: pwd

