name: Demo

on:
  push:
    branches: [main]
  
jobs:

  code:
    runs-on: ubuntu-slim

    steps:
      - name: what is your name?
        run: echo "My name is Pritesh"
  
  build:
    needs: code
    runs-on: ubuntu-slim

    steps:
      - name: what is your name?
        run: echo "My name is Pritesh"


  test:
     needs: build
     runs-on: ubuntu-slim

     steps:
       - name: version of docker & python
         run: docker --version && python --version

  deploy:
     needs: test
     runs-on: ubuntu-slim

     steps:
       - name: version of docker & python
         run: docker --version && python --version       
       
