name: Demo

on:
  push:
  branches: [main]
  
jobs:

  welcome:
    runs-on: ubuntu-slim

    steps:
      - name: what is your name?
        run: echo "My name is Pritesh"

      - name: Machine name is?
        run: echo "Machine name is $User"

   details:
     runs-on: ubuntu-slim

     steps:
       - name: version of docker & python
         run: docker --version && python --version
       
