# This will deploy thr safe tested app to Prod server
name: Deploy to Server

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.sha}}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: SSH to Server and Create the folder 
              uses: appleboy/ssh-action@v1.0.3        
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  echo "Starting Deployment..."
                  mkdir -p devops

            - name: Copy the docker compose file to the server
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                source: "docker-compose.yml"
                target: "~/devops"  

            - name: SSH to Server and run the app
              uses: appleboy/ssh-action@v1.0.3        
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    echo "Running App..."

                    sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y                 
                    sudo usermod -aG docker $USER

                    echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USER }} --password-stdin

                    export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
                    export DOCKER_TAG=${{ github.sha }}

                    cd ~/devops
                    docker compose down
                    docker compose up -d --build --force-recreate --pull always
                #   echo "Runing App..."    
                #   sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
                #   sudo usermod -aG docker $USER
                #   echo ${{ secrets.DOCKERHUB_TOKEN}} | docker login -u ${{ vars.DOCKERHUB_USER }} --password-stdin
                #   export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
                #   export DOCKER_TAG=${{ github.sha }}
                #   cd ~/devops && docker compose down && docker compose up -d --build --force-recreate --pull always
